# VectorDemo
VectorDemo : VectorDemo.o 
	g++ VectorDemo.o -o VectorDemo && make clean && ./VectorDemo && rm -rf VectorDemo
	
VectorDemo.o : VectorDemo.cpp
	g++ -c VectorDemo.cpp


# StackWithVector
StackWithVector : StackWithVector.o 
	g++ StackWithVector.o -o StackWithVector && make clean && ./StackWithVector && rm -rf StackWithVector
	
StackWithVector.o : StackWithVector.cpp
	g++ -c StackWithVector.cpp


# MapTest
MapTest : MapTest.o 
	g++ MapTest.o -o MapTest && make clean && ./MapTest && rm -rf MapTest
	
MapTest.o : MapTest.cpp
	g++ -c MapTest.cpp


# Common
clean :
	rm -rf *.o *.gch
